openapi: "3.0.0"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:4010
paths: 
  /dummy:
    summary: "dummy"
components:
  schemas:
    tags:
      type: "object"
      properties:
        tags:
          type: "array"
          items:
            type: "string"
